return {
[1] = { next id = 2, level type = 1, round max = 5, skip round = 0, monstergroup = { 1, }, },
[2] = { next id = 3, level type = 1, round max = 5, skip round = 0, monstergroup = { 2, }, },
[3] = { next id = 4, level type = 1, round max = 5, skip round = 0, monstergroup = { 3, }, },
[4] = { next id = 5, level type = 1, round max = 5, skip round = 0, monstergroup = { 4, }, },
[5] = { next id = 6, level type = 1, round max = 5, skip round = 0, monstergroup = { 5, }, },
[6] = { next id = 7, level type = 1, round max = 5, skip round = 4, monstergroup = { 6, }, },
[7] = { next id = 8, level type = 1, round max = 5, skip round = 4, monstergroup = { 7, }, },
[8] = { next id = 9, level type = 1, round max = 5, skip round = 4, monstergroup = { 8, }, },
[9] = { next id = 10, level type = 1, round max = 5, skip round = 4, monstergroup = { 9, }, },
[10] = { next id = 11, level type = 2, round max = 5, skip round = 4, monstergroup = { 10, }, },
[11] = { next id = 12, level type = 1, round max = 5, skip round = 3, monstergroup = { 11, }, },
[12] = { next id = 13, level type = 1, round max = 5, skip round = 3, monstergroup = { 12, }, },
[13] = { next id = 14, level type = 1, round max = 5, skip round = 3, monstergroup = { 13, }, },
[14] = { next id = 15, level type = 1, round max = 5, skip round = 3, monstergroup = { 14, }, },
[15] = { next id = 16, level type = 1, round max = 5, skip round = 3, monstergroup = { 15, }, },
[16] = { next id = 17, level type = 1, round max = 5, skip round = 2, monstergroup = { 16, }, },
[17] = { next id = 18, level type = 1, round max = 5, skip round = 2, monstergroup = { 17, }, },
[18] = { next id = 19, level type = 1, round max = 5, skip round = 2, monstergroup = { 18, }, },
[19] = { next id = 20, level type = 1, round max = 5, skip round = 2, monstergroup = { 19, }, },
[20] = { level type = 2, round max = 5, skip round = 2, monstergroup = { 20, }, },
}
